In [ ]:
import mesa

from mesa.visualization import SolaraViz, make_space_component
import matplotlib

# Import the local MoneyModel.py
from city_model.model import CityModel
from city_model.agents import CarAgent, SemaphoreAgent

def agent_portrayal(agent):
    return {
        "color": "tab:orange",
        "size": 50,
    }

model_params = {
    "car_count": 5
}

model1 = CityModel(car_count= 5, seed=None)

CustomCmap = matplotlib.colors.ListedColormap(((0,0,0,0), "green", "red", "yellow"))
Custom = matplotlib.colors.ListedColormap(((0,0,0,0), "deepskyblue"))

proplayer_portrayal ={"structure":{"colormap":Custom, "colorbar": False}, "semaphore":{"colormap": CustomCmap, "colorbar": False}}


SpaceGraph = make_space_component(agent_portrayal, propertylayer_portrayal=proplayer_portrayal)

page = SolaraViz(
    model1,
    components=[SpaceGraph],
    model_params=model_params,
    name="City Model",
)
# This is required to render the visualization in the Jupyter notebook
page

/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/city_model/model.py:53: UserWarning: Default value 0.0 (float64) might not be best suitable with dtype=int64.
  self.structure_layer = mesa.space.PropertyLayer("structure",self.width, self.height,np.float64(0), np.int64)
/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/city_model/model.py:53: FutureWarning: The new PropertyLayer and _PropertyGrid classes experimental. It may be changed or removed in any and all future releases, including patch releases.
We would love to hear what you think about this new feature. If you have any thoughts, share them with us here: https://github.com/projectmesa/mesa/discussions/1932
  self.structure_layer = mesa.space.PropertyLayer("structure",self.width, self.height,np.float64(0), np.int64)
/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/city_model/model.py:54: UserWarning: Defau

Cannot show ipywidgets in text

'AgentSet' object has no attribute 'moving'
Traceback (most recent call last):
  File "/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/.venv/lib/python3.13/site-packages/solara/tasks.py", line 259, in runner
    self._last_value = value = await self.function(*args, **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/.venv/lib/python3.13/site-packages/mesa/visualization/solara_viz.py", line 197, in step
    do_step()
    ~~~~~~~^^
  File "/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/.venv/lib/python3.13/site-packages/mesa/visualization/solara_viz.py", line 205, in do_step
    model.value.step()
    ~~~~~~~~~~~~~~~~^^
  File "/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/.venv/lib/python3.13/site-packages/mesa/model.py", line 113, in

Hello


In [2]:
model = CityModel(5)

print(model.grid.properties["semaphore"].data)

[[0 0 0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 3 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [3 3 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 3 0 0 0 0]
 [0 0 3 0 0 0 0 3 0 0 0 0]
 [0 0 0 0 0 3 3 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]


/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/city_model/model.py:53: UserWarning: Default value 0.0 (float64) might not be best suitable with dtype=int64.
  self.structure_layer = mesa.space.PropertyLayer("structure",self.width, self.height,np.float64(0), np.int64)
/Users/rodrigocolin/Desktop/Tec/Quinto Semestre/Agentes Inteligentes/M3Activity/M3Activity/city_model/model.py:54: UserWarning: Default value 0.0 (float64) might not be best suitable with dtype=int64.
  self.semaphore_layer = mesa.space.PropertyLayer("semaphore", self.width, self.height, np.float64(0), np.int64)
